title: Simon Niks
description: Art portfolio of Simon Niks.
projects:
  - name: test1
    date: 08-2015
    type: installation
  - name: test2
    date: 07-2016
    type: performance
  - name: test3
    date: 10-2019
    type: protype
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme